[package]
name = "hyperloop-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.13.1"
quote = "1.0.10"
syn = {version = "1.0.82", features = ["full"]}

[lib]
proc-macro = true
